[package]
name = "noir_bigcurve"
type = "lib"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
bignum = { git = "https://github.com/noir-lang/noir-bignum", tag = "v0.9.1" }
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.2.4" }
    
