[package]
name = "noir_bigcurve"
type = "lib"
authors = [""]
compiler_version = ">=0.37.0"

[dependencies]
bignum = {tag = "v0.5.0", git = "https://github.com/noir-lang/noir-bignum"}
sort = {tag = "v0.2.0", git = "https://github.com/noir-lang/noir_sort"}
