[package]
name = "noir_bigcurve"
type = "lib"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
bignum = {tag = "v0.5.3", git = "https://github.com/noir-lang/noir-bignum"}
sort = {tag = "v0.2.2", git = "https://github.com/noir-lang/noir_sort"}
